-- Create a table for public profiles
create table profiles (
  id uuid references auth.users not null primary key,
  updated_at timestamp with time zone,
  username text unique,
  full_name text,
  avatar_url text,
  website text,

  constraint username_length check (char_length(username) >= 3)
);

alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone." on profiles
  for select using (true);

create policy "Users can insert their own profile." on profiles
  for insert with check ((select auth.uid()) = id);

create policy "Users can update own profile." on profiles
  for update using ((select auth.uid()) = id);

-- Create a table for news metadata (analysis results)
create table news_metadata (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  article_url text not null unique,
  title text not null,
  source_domain text not null,
  
  -- AI Analysis Fields
  bias_score float, -- -1.0 (Left) to 1.0 (Right)
  cluster_id text, -- ID group for story clustering
  facticity_score float, -- 0.0 to 1.0
  
  -- Metadata
  published_at timestamp with time zone
);

alter table news_metadata enable row level security;

-- Everyone can read news metadata
create policy "News metadata is viewable by everyone." on news_metadata
  for select using (true);
-- Only service role (backend) should insert/update ideally, but for MVP:
create policy "Authenticated users can read news." on news_metadata
  for select using (true);


-- Create a table for bookmarks
create table bookmarks (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  article_url text not null,
  
  unique(user_id, article_url)
);

alter table bookmarks enable row level security;

create policy "Users can view own bookmarks." on bookmarks
  for select using ((select auth.uid()) = user_id);

create policy "Users can create own bookmarks." on bookmarks
  for insert with check ((select auth.uid()) = user_id);

create policy "Users can delete own bookmarks." on bookmarks
  for delete using ((select auth.uid()) = user_id);
